development:
  sessions:
    default:
      database: dd_cms_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: dd_cms_test
      hosts:
        - localhost:27017